# Generated by Django 2.1.1 on 2018-11-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20181026_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='goods/images/', verbose_name='封面图片'),
        ),
        migrations.AlterField(
            model_name='goodscategroybrand',
            name='image',
            field=models.ImageField(max_length=200, upload_to='brands/images/'),
        ),
    ]
